version: '3'

services:
  product-service:
    build:
      context: ./product-service
    ports:
      - "3001:3001"
    depends_on:
      - database

  order-service:
    build:
      context: ./order-service
    ports:
      - "3002:3002"
    depends_on:
      - database

  frontend-service:
    build:
      context: ./frontend-service
    ports:
      - "3000:3000"
    depends_on:
      - product-service
      - order-service

  database:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: "microservices_db"
      POSTGRES_USER: "microservices_user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"