version: '3'

services:
  product-service:
    build:
      context: ./product-service
    ports:
      - "3001:3001"
    volumes:
      - ./product-service:/usr/src/app
    depends_on:
      - database

  order-service:
    build:
      context: ./order-service
    ports:
      - "3002:3002"
    volumes:
      - ./order-service:/usr/src/app
    depends_on:
      - database
  
  auth-service:
    build:
      context: ./auth-service
    ports:
      - "3003:3003"
    volumes:
      - ./auth-service:/usr/src/app
    depends_on:
      - database

  admin-interface:
    build:
      context: ./admin-interface
    ports:
      - "3004:3004"
    volumes:
      - ./admin-interface:/usr/src/app
    depends_on:
      - product-service
      - order-service

  frontend-service:
    build:
      context: ./frontend-service
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-service:/usr/src/app
    depends_on:
      - product-service
      - order-service
  
  database:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: "microservices_db"
      POSTGRES_USER: "microservices_user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"